language: node_js

node_js:
  - '8'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - yarn ci-check

after_script: greenkeeper-lockfile-upload
